#!/usr/bin/python
""" Generic ngspice plotting Module

The module takes the following arguments

Schematic name --- Name of the NGspice schematic

Input_signal --- Input signal .txt file

Voltage_nodes --- voltage nodes which has to be plotted"""

# meta info
__author__ = 'Rajesh Asutkar'
__email__ = 'asutkarrajesh@sggs.ac.in'
__version__ = '-1.0'
__lastchanged__ ='17082015'

import numpy as np
import subprocess
from mpmath import mpf
import matplotlib.pyplot as plt
import sys
import time
from subprocess import call
import os

class spice():
    
    """ The Generic spice class defines all the generic spice parameters
    
    spice settings can be stored in an external file and retrieved"""

    def __init__(self,*args,**kwargs):

        """ It takes the specified Ngspice schematic file name, Input signal, Voltage nodes for plotting from the user"""
        
        if len(args) == 0:
            self.parameters = {}
            self.parameters = kwargs
        elif len(args) == 4:
            dir = os.path.dirname(__file__)
            #print (dir)
            rel_dir_name = 'defined_'+__name__ +'s'
            #print (rel_dir_name)
            filename = os.path.join(dir,rel_dir_name,args[0])
            #print (filename)
            if os.path.isfile(filename) == False:
                print('Specified file' +filename+ 'to read the beam parameters does not exist, exiting ...')
                exit()
            else:
                reader = csv.reader(open(filename, 'r'))
                self.parameters = dict(x for x in reader)       
        elif len(args) == 2:
            self.parameters = {}
            self.parameters["Schematic"]= args[0] # .cir extension
            self.parameters["Input_signal"] = args[1] #Input signal
            #self.parameters["Voltage_nodes"] = args[2] #voltage nodes to plot
        else:
            print('You have the wrong number of arguments, Please use help...')
        
        
        # Check if the some parameters are not defined or assigned to None or have the wrong type
    
        if self.parameters["Schematic"] == None:
            print ("Schematic is not defined")
            print ("Throw exception")
        #if type(self.parameters["Schematic"]) != 'str':
         #  self.parameters["Schematic"] = str( self.parameters["Schematic"])

       # if os.path.isfile(self.parameters["Schematic"]) == False:
        #        print('Specified file '+self.parameters["Schematic"]+ ' does not exist, please check the file name ...')
         #       sys.exit()
            
        if self.parameters["Input_signal"] == None:
            print ("input signal is not defined")
            print ("Throw exception")

        #self.parameters["No_of_plots"] = len(self.parameters['Voltage_nodes'])
        
        #if self.parameters["Input_signal"] is True:
        #Input_para = open("Input_signal.txt","w")
        #Input_para.write(".model filesrc filesource (file="+'"'+self.parameters["Input_signal"]+'"'+")")

        #plotng = open("plotng.txt","w")
        #time.sleep(2)
        #for N in range(0,int(self.parameters["No_of_plots"])):
         #   plotng.write("wrdata plot"+str(N)+" "+self.parameters['Voltage_nodes'][N]+'\n')
            
        
    def NGspice(self):

        """ This function will invoke NGspice 
        
        Simulate the user defined schematic file 

        Write the data at user defined voltage nodes in files named plot0, plot1... for voltage nodes given respectively

        Plot the results from user defined voltage nodes """
        
        call(["gnome-terminal","--command=ngspice"+" "+ 'topos1.cir'])  #Calls Terminal and Runs NGspice program and specified command
        call(["gnome-terminal","--command=ngspice"+" "+ 'topos2.cir'])
        call(["gnome-terminal","--command=ngspice"+" "+ 'topos3.cir'])
        call(["gnome-terminal","--command=ngspice"+" "+ 'topos4.cir'])

        time.sleep(180)  #give some time to NGspice

        self.mag = [line.rstrip('\n') for line in open('plot1.data')] #Getting data generated by NGspice in appropriate format for plotting 
        self.line1 = [line.split() for line in open('plot1.data',"r")]
        self.xpt1 = 0*range(len(self.mag))
        self.ypt1 = 0*range(len(self.mag))
        for i in range(len(self.mag)):
            self.xpt1[i] = float(self.line1[i][0])
            self.ypt1[i] = float(self.line1[i][1])
        plt.figure(1)
        plt.plot(self.xpt1,self.ypt1,'r')
        #plt.xscale('log')
        

        self.phase = [line.rstrip('\n') for line in open('plot2.data')] #Getting data generated by NGspice in appropriate format for plotting 
        self.line2 = [line.split() for line in open('plot2.data',"r")]
        self.xpt2 = 0*range(len(self.phase))
        self.ypt2 = 0*range(len(self.phase))
        for i in range(len(self.phase)):
            self.xpt2[i] = float(self.line2[i][0])
            self.ypt2[i] = float(self.line2[i][1])
        plt.plot(self.xpt2,self.ypt2,'g')
        plt.xlabel('Time /s')
        plt.ylabel('V')
        plt.grid(True)
        plt.legend(['x1','x2'],loc='upper right')

        
        if len(self.ypt1) > len(self.ypt2):
            del self.ypt1[len(self.ypt2):]
        elif len(self.ypt1) < len(self.ypt2):
            del self.ypt2[len(self.ypt1):]
        
        plt.figure(2)
        self.mag = [line.rstrip('\n') for line in open('plot3.data')] #Getting data generated by NGspice in appropriate format for plotting 
        self.line1 = [line.split() for line in open('plot3.data',"r")]
        self.xpt3 = 0*range(len(self.mag))
        self.ypt3 = 0*range(len(self.mag))
        for i in range(len(self.mag)):
            self.xpt3[i] = float(self.line1[i][0])
            self.ypt3[i] = float(self.line1[i][1])
        plt.plot(self.xpt3,self.ypt3,'r')
        #plt.xscale('log')
        
        
        self.phase = [line.rstrip('\n') for line in open('plot4.data')] #Getting data generated by NGspice in appropriate format for plotting 
        self.line2 = [line.split() for line in open('plot4.data',"r")]
        self.xpt4 = 0*range(len(self.phase))
        self.ypt4 = 0*range(len(self.phase))
        for i in range(len(self.phase)):
            self.xpt4[i] = float(self.line2[i][0])
            self.ypt4[i] = float(self.line2[i][1])
        plt.plot(self.xpt4,self.ypt4,'g')
        plt.xlabel('Time /s')
        plt.ylabel('V')
        
        if len(self.ypt3) > len(self.ypt4):
            del self.ypt3[len(self.ypt4):]
        elif len(self.ypt3) < len(self.ypt4):
            del self.ypt4[len(self.ypt1):]
      
        
        self.diff1 = self.ypt2 - self.ypt1      
        self.diff2 = self.ypt4 - self.ypt3
        self.sum1 = self.ypt2 + self.ypt1
        self.sum2 = self.ypt4 + self.ypt3

        plt.figure(3)
        plt.subplot(211)
        plt.plot(self.xpt1,self.diff1)
        plt.subplot(212)
        plt.plot(self.xpt3,self.sum1)
        plt.figure(4)
        plt.subplot(211)
        plt.plot(self.xpt1,self.diff2)
        plt.subplot(212)
        plt.plot(self.xpt3,self.sum2)
        #plt.xscale('log')
        plt.grid(True)
        #plt.xlabel('time t/sec')
        #plt.ylabel('input voltage v')
        plt.legend(['y1','y2'],loc='upper right')
        plt.show()
        os.remove("plot1.data")
        os.remove("plot2.data")
        os.remove("plot3.data")
        os.remove("plot4.data")
        #for N in range(0,int(self.parameters["No_of_plots"])):          #removing files which were created during simulation 
         #   os.remove("plot"+str(N)+".data")
        
    def __repr__(self):
        return "%s(%r)" % (self.__class__, self.__dict__)

dict_tfx1 = {'Schematic':None, 'Input_signal':None, 'Voltage_nodes': ['v(9)']}
#dict_tfx2 = {'Schematic':None, 'Input_signal':None, 'Voltage_nodes': ['V(9)']}

tfx1 = spice(**dict_tfx1)
tfx1.NGspice()

#plt.show()
