import numpy as np
import matplotlib.pyplot as plt

Z=28.0
e = 1.6e-19
R =10.0
Ts = 40.0e-9
p = np.sqrt((10.0e5))
#den = 9.0e3
const = (p*Z*e*R)/Ts
daata = open("daata/x1_coast_v.txt","w")

lines = [line.rstrip('\n') for line in open('daata/x1_coast_profile.txt')] #Getting daata generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('daata/x1_coast_profile.txt',"r")]
xpt = 0*np.ones(len(lines))
ypt = 0*np.ones(len(lines))
ypttemp = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt[i] = float(line1[i][0])/10
    #ypttemp[i] = float(line1[i][1])
    ypt[i] = const*float(line1[i][1])
    daata.write(str(xpt[i])+" "+str(ypt[i])+"\n")

daata.close()
plt.figure(1)
plt.plot(xpt,ypt)
#plt.show()

daata = open("daata/x2_coast_v.txt","w") 

lines = [line.rstrip('\n') for line in open('daata/x2_coast_profile.txt')] #Getting daata generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('daata/x2_coast_profile.txt',"r")]
xpt1 = 0*np.ones(len(lines))
ypt1 = 0*np.ones(len(lines))
for i in range(len(xpt1)):
    xpt1[i] = float(line1[i][0])/10
    ypt1[i] = const*float(line1[i][1])
    #with open("daata/x2_coast_v.txt","w") as nata:
    daata.write(str(xpt1[i])+" "+str(ypt1[i])+"\n")
plt.figure(2)
plt.plot(xpt1,ypt1)

daata = open("daata/y1_coast_v.txt","w")
lines = [line.rstrip('\n') for line in open('daata/y1_coast_profile.txt')] #Getting daata generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('daata/y1_coast_profile.txt',"r")]
xpt2 = 0*np.ones(len(lines))
ypt2 = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt2[i] = float(line1[i][0])/10
    ypt2[i] = const*float(line1[i][1])
    with open("daata/y1_coast_v.txt","a") as nata:
        nata.write(str(xpt2[i])+" "+str(ypt2[i])+"\n")
plt.figure(3)
plt.plot(xpt2,ypt2)

daata = open("daata/y2_coast_v.txt","w")

lines = [line.rstrip('\n') for line in open('daata/y2_coast_profile.txt')] #Getting daata generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('daata/y2_coast_profile.txt',"r")]
xpt3 = 0*np.ones(len(lines))
ypt3 = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt3[i] = float(line1[i][0])/10
    ypt3[i] = const*float(line1[i][1])
    with open("daata/y2_coast_v.txt","a") as nata:
        nata.write(str(xpt3[i])+" "+str(ypt3[i])+"\n")
plt.figure(4)
plt.plot(xpt3,ypt3)
plt.show()
