import numpy as np

data = open("x1_profile1.txt","w")

lines = [line.rstrip('\n') for line in open('x1_profile.txt')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('x1_profile.txt',"r")]
xpt = 0*np.ones(len(lines))
ypt = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt[i] = float(line1[i][0])
    ypt[i] = 10*float(line1[i][1])
    with open("x1_profile1.txt","a") as nata:
        nata.write(str(xpt[i])+" "+str(ypt[i])+"\n")
import matplotlib.pyplot as plt
plt.figure(1)
plt.plot(xpt,ypt)
#plt.show()

data = open("x2_profile1.txt","w")

lines = [line.rstrip('\n') for line in open('x2_profile.txt')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('x2_profile.txt',"r")]
xpt1 = 0*np.ones(len(lines))
ypt1 = 0*np.ones(len(lines))
for i in range(len(xpt1)):
    xpt1[i] = float(line1[i][0])
    ypt1[i] = 10*float(line1[i][1])
    with open("x2_profile1.txt","a") as nata:
        nata.write(str(xpt1[i])+" "+str(ypt1[i])+"\n")
plt.figure(2)
plt.plot(xpt1,ypt1)

data = open("y1_profile1.txt","w")
lines = [line.rstrip('\n') for line in open('y1_profile.txt')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('y1_profile.txt',"r")]
xpt2 = 0*np.ones(len(lines))
ypt2 = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt2[i] = float(line1[i][0])
    ypt2[i] = 10*float(line1[i][1])
    with open("y1_profile1.txt","a") as nata:
        nata.write(str(xpt2[i])+" "+str(ypt2[i])+"\n")
plt.figure(3)
plt.plot(xpt2,ypt2)

data = open("y2_profile1.txt","w")

lines = [line.rstrip('\n') for line in open('y2_profile.txt')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('y2_profile.txt',"r")]
xpt3 = 0*np.ones(len(lines))
ypt3 = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt3[i] = float(line1[i][0])
    ypt3[i] = 10*float(line1[i][1])
    with open("y2_profile1.txt","a") as nata:
        nata.write(str(xpt3[i])+" "+str(ypt3[i])+"\n")
plt.figure(4)
plt.plot(xpt3,ypt3)
plt.show()
