import numpy as np
import matplotlib.pyplot as plt
import matplotlib

plt.figure(1)
#plt.subplot(211)
lines = [line.rstrip('\n') for line in open('y1_bbq_ext.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('y1_bbq_ext.data',"r")]
xpt = 0*np.ones(len(lines))
ypt = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt[i] = float(line1[i][0])
    ypt[i] = float(line1[i][1])


lines = [line.rstrip('\n') for line in open('y2_bbq_ext.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('y1_bbq_ext.data',"r")]
xpt2 = np.zeros(len(lines))
ypt2 = np.zeros(len(lines))
for i in range(len(xpt)):
    xpt2[i] = float(line1[i][0])
    ypt2[i] = float(line1[i][1])
#plt.xscale('log')
#plt.yscale('log')
#plt.xlabel('time t/sec',fontsize=18)
#plt.ylabel('V',fontsize=18)
#plt.plot(xpt,ypt,'r',xpt2,ypt2,'b',linewidth=2)
#plt.xticks(fontsize = 15)
#plt.yticks(fontsize = 15)
#plt.grid(True)
#plt.legend(['R=1MOhm','R=50 Ohm'],loc='best')

#plt.subplot(212)

lines = [line.rstrip('\n') for line in open('y_bbq_extdiff.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('y_bbq_extdiff.data',"r")]
xpt4 = 0*np.ones(len(lines))
ypt4= 0*np.ones(len(lines))
for i in range(len(xpt4)):
    xpt4[i] = float(line1[i][0])
    ypt4[i] = float(line1[i][1])

#plt.xscale('log')
plt.xlabel('time t/ usec',fontsize=15)
plt.ylabel('V',fontsize=15)
plt.plot(xpt,ypt,xpt2,ypt2,xpt4,ypt4,linewidth=1.5)
plt.legend(['Input y1','Input y2','in2','BBQ output'],loc='best',fontsize=15)
#plt.figure(1)
#plt.plot(xpt,ypt2-ypt,xpt,ypt2+ypt)
#plt.figure(2)
#plt.plot(xpt3,ypt3-ypt4,xpt3,ypt3+ypt4)
plt.xticks(fontsize = 15) 
plt.yticks(fontsize = 15) 
plt.grid(True)
plt.show()

