import numpy as np
import matplotlib.pyplot as plt
import matplotlib

plt.figure()
#plt.subplot(211)
lines = [line.rstrip('\n') for line in open('daata/x1_profileext_volt2.txt')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('daata/x1_profileext_volt2.txt',"r")]
xpt = 0*np.ones(len(lines))
ypt = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt[i] = float(line1[i][0])/(1e6)
    ypt[i] = float(line1[i][1])


lines = [line.rstrip('\n') for line in open('x1_ext.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('x1_ext.data',"r")]
xpt2 = np.zeros(len(lines))
ypt2 = np.zeros(len(lines))
for i in range(len(xpt2)):
    xpt2[i] = float(line1[i][0])/(1e6)
    ypt2[i] = float(line1[i][1])
#plt.xscale('log')
#plt.yscale('log')
#plt.xlabel('time t/sec',fontsize=18)
#plt.ylabel('V',fontsize=18)
#plt.plot(xpt,ypt,'r',xpt2,ypt2,'b',linewidth=2)
#plt.xticks(fontsize = 15)
#plt.yticks(fontsize = 15)
#plt.grid(True)
#plt.legend(['R=1MOhm','R=50 Ohm'],loc='best')

#plt.subplot(212)

lines = [line.rstrip('\n') for line in open('plot3.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('plot3.data',"r")]
xpt3 = 0*np.ones(len(lines))
ypt3 = 0*np.ones(len(lines))
for i in range(len(xpt3)):
    xpt3[i] = float(line1[i][0])/(1e6)
    ypt3[i] = float(line1[i][1])

#plt.xscale('log')
plt.xlabel('time t/ usec',fontsize=25)
plt.ylabel('V',fontsize=25)
plt.plot(xpt2,ypt2,'b',xpt,ypt,'r',linewidth=2)
plt.legend(['Topos output','Topos input'],loc='best',fontsize=20)
#plt.figure(1)
#plt.plot(xpt,ypt2-ypt,xpt,ypt2+ypt)
#plt.figure(2)
#plt.plot(xpt3,ypt3-ypt4,xpt3,ypt3+ypt4)
plt.xticks(fontsize = 25) 
plt.yticks(fontsize = 25) 
plt.grid(True)
plt.show()

