import numpy as np


lines = [line.rstrip('\n') for line in open('results/bunch_5_1/x1_5_1.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('results/bunch_5_1/x1_5_1.data',"r")]
xpt = 0*np.ones(len(lines))
ypt = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt[i] = float(line1[i][0])
    ypt[i] = float(line1[i][1])


lines = [line.rstrip('\n') for line in open('x22.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('x22.data',"r")]
xpt2 = np.zeros(len(lines))
ypt2 = np.zeros(len(lines))
for i in range(len(xpt)):
    xpt2[i] = float(line1[i][0])
    ypt2[i] = float(line1[i][1])

lines = [line.rstrip('\n') for line in open('plot0.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('plot0.data',"r")]
xpt3 = 0*np.ones(len(lines))
ypt3 = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt3[i] = float(line1[i][0])
    ypt3[i] = float(line1[i][1])


lines = [line.rstrip('\n') for line in open('plot1.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('plot1.data',"r")]
xpt4 = 0*np.ones(len(lines))
ypt4 = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt4[i] = float(line1[i][0])
    ypt4[i] = float(line1[i][1])

import matplotlib.pyplot as plt
plt.figure(1)
plt.plot(xpt,ypt2-ypt,xpt,ypt2+ypt)
plt.figure(2)
plt.plot(xpt3,ypt3-ypt4,xpt3,ypt3+ypt4)
plt.show()
