from scipy.fftpack import fft
import numpy as np
import matplotlib.pyplot as plt



Fs = 1.0e9
lines = [line.rstrip('\n') for line in open('x2_bbq_ext.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('x2_bbq_ext.data',"r")]
xpt = 0*np.ones(len(lines))
ypt = 0*np.ones(len(lines))
for i in range(len(xpt)):
    xpt[i] = float(line1[i][0])
    ypt[i] = float(line1[i][1])

yf = fft(ypt)
f = np.arange(0,Fs,Fs/len(yf))
plt.figure(1)
plt.plot(f,abs(yf))

lines = [line.rstrip('\n') for line in open('ffy.data')] #Getting data generated by NGspice in appropriate format for plotting 
line1 = [line.split() for line in open('ffy.data',"r")]
xpt1 = 0*np.ones(len(lines))
ypt1 = 0*np.ones(len(lines))
for i in range(len(xpt1)):
    xpt1[i] = float(line1[i][0])
    ypt1[i] = float(line1[i][1])
    
yf1 = fft(ypt1)
f1 = np.arange(0,Fs,Fs/len(yf1))
plt.figure(2)
plt.plot(abs(yf1))
plt.show()
